#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import secrets
import shutil
import stat
import string
import subprocess
import sys
from pathlib import Path


GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
BOLD = "\033[1m"
RESET = "\033[0m"

EXPECTED_USER = "vt_user"
CERT_FILE_NAME = "Cisco_Umbrella_Root_CA.crt"
DEPLOY_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DEPLOY_DIR.parents[1]

FAST_DATA_ROOT = Path("/mnt/fast_data")
DATA_LAKE_ROOT = Path("/mnt/data_lake")

DEFAULTS = {
    "POSTGRES_ADMIN_USER": "postgres",
    "AIRFLOW_DB_NAME": "airflow",
    "AIRFLOW_DB_USER": "airflow",
    "INGESTION_DB_NAME": "ingestion_metadata",
    "INGESTION_DB_USER": "ingestion_app",
    "AIRFLOW_ADMIN_USERNAME": "admin",
    "AIRFLOW_ADMIN_EMAIL": "airflow-admin@example.com",
    "AIRFLOW_ADMIN_FIRSTNAME": "Airflow",
    "AIRFLOW_ADMIN_LASTNAME": "Admin",
    "MINIO_ROOT_USER": "admin",
    "MINIO_SCHEME": "http",
    "MINIO_BRONZE_BUCKET": "bronze",
    "MINIO_LANDING_BUCKET": "landing",
    "MINIO_SILVER_BUCKET": "silver",
    "MINIO_GOLD_BUCKET": "gold",
    "MINIO_QUARANTINE_BUCKET": "quarantine",
    "POSTGRES_DATA_PATH": "/mnt/fast_data/postgres/data",
    "AIRFLOW_DAGS_PATH": "/mnt/fast_data/airflow/dags",
    "AIRFLOW_LOGS_PATH": "/mnt/fast_data/airflow/logs",
    "AIRFLOW_PLUGINS_PATH": "/mnt/fast_data/airflow/plugins",
    "AIRFLOW_CONFIG_PATH": "/mnt/fast_data/airflow/config",
    "INGESTION_CONFIG_PATH": "/mnt/fast_data/ingestion-framework/config",
    "INGESTION_STATE_PATH": "/mnt/fast_data/ingestion-framework/state",
    "MINIO_DATA_PATH": "/mnt/data_lake/minio/data",
    "MINIO_CERTS_PATH": "/mnt/data_lake/minio/certs",
    "POSTGRES_HOST_BIND": "127.0.0.1",
    "POSTGRES_HOST_PORT": "5432",
    "AIRFLOW_HOST_BIND": "0.0.0.0",
    "AIRFLOW_HOST_PORT": "8080",
    "MINIO_API_HOST_BIND": "0.0.0.0",
    "MINIO_API_HOST_PORT": "9000",
    "MINIO_CONSOLE_HOST_BIND": "0.0.0.0",
    "MINIO_CONSOLE_HOST_PORT": "9001",
    "OPENBAO_ADDR": "http://openbao:8200",
    "OPENBAO_TOKEN_FILE_PATH": "/mnt/fast_data/openbao/ingestion-framework.token",
    "INGESTION_AUDIT_DB_URL_REF": "openbao:secret/data/ingestion-framework/audit#url",
    "INSTALL_MSSQL_ODBC": "true",
}

SECRET_KEYS = {
    "POSTGRES_ADMIN_PASSWORD": 32,
    "AIRFLOW_DB_PASSWORD": 32,
    "INGESTION_DB_PASSWORD": 32,
    "MINIO_ROOT_PASSWORD": 32,
    "AIRFLOW_ADMIN_PASSWORD": 24,
    "AIRFLOW_SECRET_KEY": 48,
}


def log_info(message: str) -> None:
    print(f"{BLUE}{BOLD}[*]{RESET} {message}")


def log_success(message: str) -> None:
    print(f"{GREEN}{BOLD}[+]{RESET} {message}")


def log_warning(message: str) -> None:
    print(f"{YELLOW}{BOLD}[!]{RESET} {message}")


def log_error(message: str) -> None:
    print(f"{RED}{BOLD}[-]{RESET} {message}")


def run_cmd(
    command: list[str],
    *,
    sudo: bool = False,
    check: bool = True,
    cwd: Path | None = None,
) -> subprocess.CompletedProcess[str]:
    if sudo and os.getuid() != 0:
        command = ["sudo", *command]
    result = subprocess.run(
        command,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        cwd=cwd,
    )
    if check and result.returncode != 0:
        log_error(f"Command failed: {' '.join(command)}")
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr)
        raise SystemExit(result.returncode)
    return result


def secure_token(length: int) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def fernet_key() -> str:
    import base64

    return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii")


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env(path: Path, values: dict[str, str]) -> None:
    ordered_keys = [*DEFAULTS.keys(), *SECRET_KEYS.keys(), "AIRFLOW_UID"]
    emitted = set()
    lines = [
        "# Generated by deploy/single-node-airflow/install_platform.py.",
        "# Existing values are preserved on re-run unless --rotate-secrets is used.",
    ]
    for key in ordered_keys:
        if key in values:
            lines.append(f"{key}={values[key]}")
            emitted.add(key)
    for key in sorted(set(values) - emitted):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def build_env(rotate_secrets: bool) -> dict[str, str]:
    env_path = DEPLOY_DIR / ".env"
    values = read_env(env_path)
    for key, value in DEFAULTS.items():
        values.setdefault(key, value)
    values.setdefault("AIRFLOW_UID", "50000")
    for key, length in SECRET_KEYS.items():
        if rotate_secrets or key not in values:
            values[key] = secure_token(length)
    if rotate_secrets or "AIRFLOW_FERNET_KEY" not in values:
        values["AIRFLOW_FERNET_KEY"] = fernet_key()
    return values


def verify_user(yes: bool) -> None:
    current_user = os.environ.get("USER", "")
    if current_user == EXPECTED_USER:
        return
    log_warning(f"This script is optimized to run as '{EXPECTED_USER}'. Current user is '{current_user}'.")
    if not yes:
        choice = input("Proceed anyway? (y/N): ").strip().lower()
        if choice != "y":
            raise SystemExit(1)


def validate_mounts(skip_mount_check: bool) -> None:
    if skip_mount_check:
        log_warning("Skipping mount validation by request.")
        return
    for mount in (FAST_DATA_ROOT, DATA_LAKE_ROOT):
        if not mount.exists():
            log_error(f"Required mount path does not exist: {mount}")
            raise SystemExit(1)
        result = run_cmd(["findmnt", "--target", str(mount)], check=False)
        if result.returncode != 0:
            log_error(f"Required path is not a mounted filesystem: {mount}")
            raise SystemExit(1)
    log_success("Validated fast_data and data_lake mounts.")


def install_ca_certificate(yes: bool) -> None:
    source = DEPLOY_DIR / CERT_FILE_NAME
    if not source.exists():
        source = Path.cwd() / CERT_FILE_NAME
    if not source.exists():
        log_warning(f"Could not find {CERT_FILE_NAME}.")
        if not yes:
            choice = input("Proceed without importing the Cisco Umbrella CA? (y/N): ").strip().lower()
            if choice != "y":
                raise SystemExit(0)
        return

    log_info("Installing Cisco Umbrella CA into host trust store.")
    target = Path("/usr/local/share/ca-certificates") / CERT_FILE_NAME
    run_cmd(["cp", str(source), str(target)], sudo=True)
    run_cmd(["update-ca-certificates"], sudo=True)
    shutil.copy2(source, DEPLOY_DIR / "config" / CERT_FILE_NAME)
    log_success("CA installed on host and copied into deployment config.")


def install_docker() -> None:
    if shutil.which("docker"):
        log_success("Docker is already installed.")
        return
    log_info("Installing Docker Engine and Compose plugin.")
    run_cmd(["apt-get", "update"], sudo=True)
    run_cmd(
        ["apt-get", "install", "-y", "apt-transport-https", "ca-certificates", "curl", "gnupg", "lsb-release"],
        sudo=True,
    )
    run_cmd(["install", "-m", "0755", "-d", "/etc/apt/keyrings"], sudo=True)
    run_cmd(
        [
            "bash",
            "-c",
            "curl -fsSL https://download.docker.com/linux/ubuntu/gpg "
            "| gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg",
        ],
        sudo=True,
    )
    arch = run_cmd(["dpkg", "--print-architecture"]).stdout.strip()
    codename = run_cmd(["lsb_release", "-cs"]).stdout.strip()
    repo = (
        f"deb [arch={arch} signed-by=/etc/apt/keyrings/docker.gpg] "
        f"https://download.docker.com/linux/ubuntu {codename} stable"
    )
    run_cmd(["bash", "-c", f"echo '{repo}' > /etc/apt/sources.list.d/docker.list"], sudo=True)
    run_cmd(["apt-get", "update"], sudo=True)
    run_cmd(["apt-get", "install", "-y", "docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"], sudo=True)
    run_cmd(["systemctl", "enable", "--now", "docker"], sudo=True)
    run_cmd(["usermod", "-aG", "docker", EXPECTED_USER], sudo=True)
    log_success("Docker Engine and Compose plugin installed.")


def create_directories(values: dict[str, str]) -> None:
    paths = [
        values["POSTGRES_DATA_PATH"],
        values["AIRFLOW_DAGS_PATH"],
        values["AIRFLOW_LOGS_PATH"],
        values["AIRFLOW_PLUGINS_PATH"],
        values["AIRFLOW_CONFIG_PATH"],
        values["INGESTION_CONFIG_PATH"],
        values["INGESTION_STATE_PATH"],
        values["MINIO_DATA_PATH"],
        values["MINIO_CERTS_PATH"],
        str(Path(values["OPENBAO_TOKEN_FILE_PATH"]).parent),
    ]
    for path in paths:
        run_cmd(["mkdir", "-p", path], sudo=True)
    run_cmd(["chown", "-R", f"{EXPECTED_USER}:0", str(FAST_DATA_ROOT)], sudo=True)
    run_cmd(["chown", "-R", f"{EXPECTED_USER}:0", str(DATA_LAKE_ROOT)], sudo=True)
    run_cmd(["chmod", "-R", "775", str(FAST_DATA_ROOT)], sudo=True)
    run_cmd(["chmod", "-R", "775", str(DATA_LAKE_ROOT)], sudo=True)
    log_success("Created and permissioned platform directories.")


def write_generated_scripts() -> None:
    generated = DEPLOY_DIR / "generated"
    generated.mkdir(exist_ok=True)

    postgres_init_dir = generated / "postgres-init"
    postgres_init_dir.mkdir(exist_ok=True)
    postgres_init = postgres_init_dir / "01-create-databases.sh"
    postgres_init.write_text(
        """#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
SELECT 'CREATE USER "' || '${AIRFLOW_DB_USER}' || '" WITH PASSWORD ''' || '${AIRFLOW_DB_PASSWORD}' || ''''
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${AIRFLOW_DB_USER}')\\gexec
SELECT 'CREATE DATABASE "' || '${AIRFLOW_DB_NAME}' || '" OWNER "' || '${AIRFLOW_DB_USER}' || '"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${AIRFLOW_DB_NAME}')\\gexec
SELECT 'CREATE USER "' || '${INGESTION_DB_USER}' || '" WITH PASSWORD ''' || '${INGESTION_DB_PASSWORD}' || ''''
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${INGESTION_DB_USER}')\\gexec
SELECT 'CREATE DATABASE "' || '${INGESTION_DB_NAME}' || '" OWNER "' || '${INGESTION_DB_USER}' || '"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${INGESTION_DB_NAME}')\\gexec
EOSQL
""",
    )
    postgres_init.chmod(0o755)

    minio_bootstrap = generated / "minio-bootstrap.sh"
    minio_bootstrap.write_text(
        """#!/bin/sh
set -eu

until mc alias set local "${MINIO_SCHEME}://minio:9000" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" >/dev/null 2>&1; do
  sleep 2
done
mc ready local
for bucket in "$MINIO_BRONZE_BUCKET" "$MINIO_LANDING_BUCKET" "$MINIO_SILVER_BUCKET" "$MINIO_GOLD_BUCKET" "$MINIO_QUARANTINE_BUCKET"; do
  if [ -n "$bucket" ]; then
    mc mb --ignore-existing "local/$bucket"
  fi
done
""",
    )
    minio_bootstrap.chmod(0o755)

    airflow_bootstrap = generated / "airflow-bootstrap.sh"
    airflow_bootstrap.write_text(
        """#!/usr/bin/env bash
set -euo pipefail

airflow db migrate

airflow users create \
  --username "$AIRFLOW_ADMIN_USERNAME" \
  --password "$AIRFLOW_ADMIN_PASSWORD" \
  --firstname "$AIRFLOW_ADMIN_FIRSTNAME" \
  --lastname "$AIRFLOW_ADMIN_LASTNAME" \
  --role Admin \
  --email "$AIRFLOW_ADMIN_EMAIL" || true

airflow connections delete minio_default >/dev/null 2>&1 || true
airflow connections add minio_default \
  --conn-type aws \
  --conn-login "$MINIO_ROOT_USER" \
  --conn-password "$MINIO_ROOT_PASSWORD" \
  --conn-extra "{\"endpoint_url\":\"${MINIO_SCHEME}://minio:9000\"}"

airflow connections delete ingestion_metadata >/dev/null 2>&1 || true
airflow connections add ingestion_metadata \
  --conn-type postgres \
  --conn-host postgres \
  --conn-port 5432 \
  --conn-schema "$INGESTION_DB_NAME" \
  --conn-login "$INGESTION_DB_USER" \
  --conn-password "$INGESTION_DB_PASSWORD"

airflow variables set ingestion_bronze_bucket "$MINIO_BRONZE_BUCKET"
airflow variables set ingestion_minio_endpoint "${MINIO_SCHEME}://minio:9000"
""",
    )
    airflow_bootstrap.chmod(0o755)
    log_success("Generated Postgres, MinIO, and Airflow bootstrap scripts.")


def sync_ingestion_dags(values: dict[str, str]) -> None:
    sources = [
        DEPLOY_DIR / "dags" / "ingestion_smoke_test.py",
        *sorted((DEPLOY_DIR / "dags" / "generated").glob("*.py")),
    ]
    for source in sources:
        target = Path(values["AIRFLOW_DAGS_PATH"]) / source.name
        run_cmd(["cp", str(source), str(target)], sudo=True)
        run_cmd(["chown", f"{EXPECTED_USER}:0", str(target)], sudo=True)
        run_cmd(["chmod", "664", str(target)], sudo=True)
    log_success(f"Installed {len(sources)} DAGs at {values['AIRFLOW_DAGS_PATH']}.")


def compose_config() -> None:
    log_info("Validating Docker Compose configuration.")
    run_cmd(["docker", "compose", "--env-file", ".env", "config"], check=True, cwd=DEPLOY_DIR)
    log_success("Docker Compose configuration is valid.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap the single-node Airflow ingestion platform.")
    parser.add_argument("--yes", action="store_true", help="Accept prompts for non-destructive choices.")
    parser.add_argument("--skip-docker-install", action="store_true", help="Do not install Docker if missing.")
    parser.add_argument("--skip-mount-check", action="store_true", help="Do not require /mnt paths to be mounted.")
    parser.add_argument("--rotate-secrets", action="store_true", help="Regenerate all generated secrets.")
    parser.add_argument(
        "--sync-dags-only",
        action="store_true",
        help="Copy generated DAGs to the configured Airflow DAG folder and exit.",
    )
    args = parser.parse_args()

    print(f"{BOLD}Single-Node Airflow Ingestion Platform Bootstrap{RESET}")
    if args.sync_dags_only:
        values = read_env(DEPLOY_DIR / ".env")
        if "AIRFLOW_DAGS_PATH" not in values:
            log_error("deploy/single-node-airflow/.env is missing AIRFLOW_DAGS_PATH. Run full bootstrap first.")
            return 2
        sync_ingestion_dags(values)
        log_success("DAG sync complete.")
        return 0

    verify_user(args.yes)
    validate_mounts(args.skip_mount_check)
    install_ca_certificate(args.yes)
    if args.skip_docker_install:
        log_warning("Skipping Docker installation by request.")
    else:
        install_docker()
    values = build_env(args.rotate_secrets)
    write_env(DEPLOY_DIR / ".env", values)
    create_directories(values)
    write_generated_scripts()
    sync_ingestion_dags(values)
    compose_config()

    log_success("Bootstrap files and directories are ready.")
    print(f"Next: cd {DEPLOY_DIR} && docker compose --env-file .env up -d --build")
    print(f"Airflow admin: {values['AIRFLOW_ADMIN_USERNAME']} / see deploy/single-node-airflow/.env")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
